name: pipline-job

on:
  push:
  workflow_dispatch:

jobs:
  Run_Full_Pipeline:
    name: Run Full Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.0

    - name: Check Python Version
      run: python3 --version

    - name: Set up Virtual Environment and Install Dependencies
      shell: bash
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install pandas matplotlib seaborn numpy scikit-learn

    - name: Run Python Script
      shell: bash
      run: |
        source venv/bin/activate
        python3 plant_species.py
